apiVersion: v1
kind: Pod
metadata:
  name: postgresql
  labels:
    name: postgresql
spec:
  containers:
    - resources:
        limits:
          cpu: 1
      image: postgres:9.4
      name: postgresql
      env:
        - name: POSTGRES_DB
          value: mydb
        - name: POSTGRES_USER
          value: admin
        - name: POSTGRES_PASSWORD
          value: admin
      ports:
        - containerPort: 5432
          name: postgresql
